### ISSUE TITLE
Default buffer using max; should it use min?

### ISSUE THREAD

**Issue by once-ler** [outvoider/Integro#1]
https://github.com/outvoider/Integro/blob/master/Integro/Access.hpp#L295

When allocating buffer size, it seems to choose the max between the length of the field and 32.

If I have an empty string, it is writing a buffer of 32 spaces in Mongo.
However, my application is expect an empty string.

**Comment by outvoider** [comment]
min/max are not related. fixed the problem by trimming leading and trailing spaces after freetds conversion.
