### ISSUE TITLE
Remove "processed" field as datum for hashing

### ISSUE THREAD

**Issue by once-ler** [outvoider/Integro#2]
The __processed__ field, in the current implementation, is mutable.  Please remove it as part of datum for hashing.

**Comment by outvoider** [comment]
Sure. Have you considered the layered design I suggested?

{
    _id: "",
    descriptor: "",
    processed:"",
    ... other metadata,
    
    data:
    {
        original data
    }
}

This way there is no possibility for name clashes. There is also more flexibility, because changing metadata will not affect unrelated parts of code, for instance hashing.
